greads/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_URL)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views
from . import models


app_name= 'home'

urlpatterns = [
	#home/
	url(r'^$' , views.IndexView.as_view(), name='index'),
	
	#home/2
	url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name ='detail' ) ,
	
	#home/addbook
	url(r'^add/$' , views.BookCreate.as_view(), name='create_book'),
	
	#home/2/update
	url(r'^(?P<pk>[0-9]+)/update$' , views.BookUpdate.as_view() , name ='update' ) ,
	
	#home/2/delete
	url(r'^(?P<pk>[0-9]+)/delete$' , views.BookDelete.as_view() , name ='delete' ) ,
	
	#home/logout
	url(r'^logout$' , views.IndexView.as_view(), name='logout_user'),
]

home/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class book(models.Model):
	book_title= models.CharField(max_length=250)
	book_author= models.CharField(max_length=250)
	price=models.IntegerField(default=0)
	genre=models.CharField(max_length=250)
	book_logo=models.FileField()
	is_favourite=models.BooleanField(default=False)
	
	def get_absolute_url(self):
		return reverse('home:detail', kwargs={'pk':self.pk})

##	def __str__ (self):
##		return str(self.book_title+'-'+self.book_author+'-'+self.price+'-'+self.genre);*/

home/forms.py
from django.contrib.auth.models import User
from django import forms 


class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=['username','e-mail','password']

home/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.urls import reverse_lazy
from .models import book

class IndexView(generic.ListView):
	template_name='home/index.html'
	
	def get_queryset(self):
		return book.objects.all()


class DetailView(generic.DetailView):
	model=book
	template_name='home/detail.html'

class BookCreate(CreateView):
	model=book
	template_name='home/create_book.html'
	fields=['book_author','book_title','genre','book_logo']


class BookUpdate(UpdateView):
	model=book
	fields=['book_author','book_title','genre','book_logo']

class BookDelete(DeleteView):
	model=book
	success_url=reverse_lazy('home:index')

class UserFormView(DeleteView):
	form_class= UserFormView
	template_name='home/registration_form.html'

	def get(self, request):
		form=self.form_class(None)
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form=self.form_class(request.POST)

		if form.is_valid():
			user=form.save(commit= False)

			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}greads{% endblock %}</title>
    {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
        
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>        
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">greads</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block books_active %}{% endblock %}"><a href="{% url 'home:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Books</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'home:create_book' %}">
 
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Book
                    </a>
                </li>
                <li>
                    <a href="{% url 'home:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/create_book.html
{% extends 'home/base.html' %}
{% block title %}Add a New Book{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Viberr?</h3>
                    <p>Viberr is an app that allows you to upload and store all of your home on the cloud.</p>
                    <h3>How do I add home?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

home/templates/home/detail.html
{% extends 'home/base.html' %}

{% block body %}

	<ul>
		
	</ul>
{% endblock %}

home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}Books{% endblock %}

{% block body %}
<div class="books-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
           
        </div>
        {% if object_list %}
            {% for bookvar in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'home:detail' bookvar.id %}">
                            <img src="{{ bookvar.book_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ bookvar.book_title }}</h2>
                            <h4>{{ bookvar.author }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'home:detail' bookvar.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'home:delete' bookvar.id%}" method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="book_id" value="{{ bookvar.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'home:index'  %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if bookvar.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'home:create_book' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    
{% endblock %}			